language: c++
dist: trusty

compiler:
  - clang
  - gcc

install: 
  - sudo apt-get update || true
  - sudo apt-get install build-essential
  - sudo apt-get install libglib2.0 libxml2-dev libpcap-dev librrd-dev redis-server libsqlite3-dev libhiredis-dev libgeoip-dev libcurl4-openssl-dev libzmq3-dev git

before_script:
  - git clone https://github.com/ntop/nDPI.git; cd nDPI; ./autogen.sh; make; cd ..
  - ./autogen.sh

script:
  - ./configure
  - make
 